version: "3.5"
services:
    mysql:
      restart: unless-stopped
      image: mysql:8.0
      container_name: exercise-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=exerise
        - MYSQL_DATABASE=exerise
        - MYSQL_USER=exerise
        - MYSQL_PASSWORD=exerise
      ports:
        - "9000:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - exercise_network
    webserver:
      restart: unless-stopped
      image: nginx:alpine
      container_name: exercise-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9001:80"
      networks:
        - exercise_network
    php-fpm:
      restart: unless-stopped
      build: docker/php-fpm
      container_name: exercise-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      networks:
        - exercise_network
    redis:
      restart: unless-stopped
      container_name: exercise-redis
      image: redis:alpine
      ports:
        - "9002:6379"
      networks:
        - exercise_network

networks:
  exercise_network:
    name: exercise_network
    ipam:
      config:
        - subnet: 172.67.0.0/24
